exo3: exo3.o
	gcc -o exo3 exo3.o
exo3.o: exo3.c
	gcc -o exo3.o -c exo3.c
exo2: exo2.o
	gcc -o exo2 exo2.o
exo2.o: exo2.c
	gcc -o exo2.o -c exo2.c
exo1: exo1.o
	gcc -o exo1 exo1.o
exo1.o: exo1.c
	gcc -o exo1.o -c exo1.c


